#!/bin/sh
# NH_SETUP_VERSION: 2.0 nextgen
# Profile: Arch ARM64 v2.0 full; Kali ARM64 v2.0 full
# NetHunter setup v2.0 nextgen — dual Arch ARM64 + Kali ARM64 chroot environment
# Target: OnePlus 7 Pro (GM1911) / Android 16 / LineageOS 23.2 / arm64-v8a

NH_SETUP_VERSION="${NH_SETUP_VERSION:-2.0}"
NH_SETUP_PROFILE="${NH_SETUP_PROFILE:-full}"
NH_DEVICE_NAME="${NH_DEVICE_NAME:-OnePlus 7 Pro GM1911}"
NH_ANDROID_RELEASE="${NH_ANDROID_RELEASE:-16}"
NH_ANDROID_ABI="${NH_ANDROID_ABI:-arm64-v8a}"
NH_DEVICE_CODENAME="${NH_DEVICE_CODENAME:-guacamole}"
NH_LINEAGE_VERSION="${NH_LINEAGE_VERSION:-23.2}"

DEVICE_IP="${DEVICE_IP:-10.0.0.113}"
ADB_PORT="${ADB_PORT:-52104}"
ADB_SERIAL="${ADB_SERIAL:-$DEVICE_IP:$ADB_PORT}"
ROOT_SU="${ROOT_SU:-/debug_ramdisk/su}"

NHSYSTEM="${NHSYSTEM:-/data/local/nhsystem}"
NHROOTS="${NHROOTS:-$NHSYSTEM/roots}"
NHWORK="${NHWORK:-$NHSYSTEM/workspaces/main}"
ARCH_ROOT_NAME="${ARCH_ROOT_NAME:-archlinux}"
KALI_ROOT_NAME="${KALI_ROOT_NAME:-kali-arm64}"
ARCH_ROOT_PATH="${ARCH_ROOT_PATH:-$NHROOTS/$ARCH_ROOT_NAME}"
KALI_ROOT_PATH="${KALI_ROOT_PATH:-$NHROOTS/$KALI_ROOT_NAME}"

ARCH_LABEL="${ARCH_LABEL:-Arch ARM64 v$NH_SETUP_VERSION ($NH_SETUP_PROFILE)}"
KALI_LABEL="${KALI_LABEL:-Kali ARM64 v$NH_SETUP_VERSION ($NH_SETUP_PROFILE)}"
NH_LABEL="${NH_LABEL:-NetHunter setup v$NH_SETUP_VERSION ($NH_SETUP_PROFILE)}"

ARCH_SSH_USER="${ARCH_SSH_USER:-archlinux}"
ARCH_SSH_PORT="${ARCH_SSH_PORT:-2222}"
KALI_SSH_USER="${KALI_SSH_USER:-kali}"
KALI_SSH_PORT="${KALI_SSH_PORT:-22}"
TERMUX_SSH_USER="${TERMUX_SSH_USER:-u0_a171}"
TERMUX_SSH_PORT="${TERMUX_SSH_PORT:-8022}"
