# NH_SETUP_VERSION: 2.0 default
# Profile: Arch ARM64 v2.0 default; Kali ARM64 v2.0 default
# Termux zsh config — full dev environment
# Generated by nethunter-setup — safe to customize

PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
export HOME="${HOME:-/data/data/com.termux/files/home}"
export NHSYSTEM=/data/local/nhsystem
export NHWORKSPACE=$NHSYSTEM/workspaces/main
export NH_SU="${NH_SU:-/debug_ramdisk/su}"

# ── Path ──────────────────────────────────────────────────────────────────────
case ":$PATH:" in *":$PREFIX/bin:"*) ;; *) PATH="$PREFIX/bin:$PATH" ;; esac
case ":$PATH:" in *":$PREFIX/bin/applets:"*) ;; *) PATH="$PREFIX/bin/applets:$PATH" ;; esac
case ":$PATH:" in *":/system/bin:"*) ;; *) PATH="/system/bin:$PATH" ;; esac
export PATH
export LD_LIBRARY_PATH="$PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export TMPDIR="${TMPDIR:-$PREFIX/tmp}"
mkdir -p "$TMPDIR" 2>/dev/null || true

# Avoid Termux LD_PRELOAD leaking into Android/vendor toybox commands in SSH.
if [ -n "${SSH_CONNECTION:-}" ] || [ -n "${SSH_CLIENT:-}" ]; then
    unset LD_PRELOAD
fi

# ── History ───────────────────────────────────────────────────────────────────
HISTSIZE=10000
SAVEHIST=10000
HISTFILE="$HOME/.zsh_history"
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY

# ── Completion ────────────────────────────────────────────────────────────────
autoload -Uz compinit
compinit -d ~/.zcompdump 2>/dev/null || true
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# ── Key Bindings ──────────────────────────────────────────────────────────────
bindkey -e
bindkey '^R' history-incremental-search-backward
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward

# ── NetHunter Aliases ─────────────────────────────────────────────────────────
[ -f "$HOME/.nh-aliases.zsh" ] && source "$HOME/.nh-aliases.zsh"

# ── fzf ───────────────────────────────────────────────────────────────────────
[ -f "$PREFIX/share/fzf/key-bindings.zsh" ] && source "$PREFIX/share/fzf/key-bindings.zsh"
[ -f "$PREFIX/share/fzf/completion.zsh" ]   && source "$PREFIX/share/fzf/completion.zsh"

# ── Starship Prompt ───────────────────────────────────────────────────────────
if command -v starship >/dev/null 2>&1; then
    eval "$(starship init zsh)"
else
    PROMPT='%F{cyan}%n@termux%f:%F{blue}%~%f %# '
fi

# ── Termux-specific helpers ───────────────────────────────────────────────────
alias pkg-update='pkg update && pkg upgrade -y'
alias termux-info='termux-info 2>/dev/null || uname -a'
